#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp pod-babashka-aws /tmp/release
VERSION=$(cat resources/POD_BABASHKA_AWS_VERSION)

cd /tmp/release

arch="amd64"

if [ "$BABASHKA_STATIC" = "true" ]; then
    arch="$arch-static"
fi

## release binary as zip archive

zip "pod-babashka-aws-$VERSION-$APP_PLATFORM-$arch.zip" pod-babashka-aws

## cleanup

rm pod-babashka-aws
