#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp pod-babashka-aws /tmp/release
VERSION=$(cat resources/POD_BABASHKA_AWS_VERSION)

cd /tmp/release

## release binary as zip archive

zip "pod-babashka-aws-$VERSION-$APP_PLATFORM-amd64.zip" pod-babashka-aws

## cleanup

rm pod-babashka-aws
