#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp pod-babashka-buddy /tmp/release
VERSION=$(cat resources/POD_BABASHKA_BUDDY_VERSION)

cd /tmp/release

## release binary as zip archive

zip "pod-babashka-buddy-$VERSION-$APP_PLATFORM-amd64.zip" pod-babashka-buddy

## cleanup

rm pod-babashka-buddy
