#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

clojure -X:native:uberjar

ZLIB_VERSION="1.2.11"

wget "https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz"
tar xf "zlib-${ZLIB_VERSION}.tar.gz"
cd "zlib-${ZLIB_VERSION}"
CC=musl-gcc ./configure --static --prefix=/usr/lib/x86_64-linux-musl/
make CC=musl-gcc
sudo make install
cd ..

"$GRAALVM_HOME/bin/gu" install native-image

args=(
    "-cp" "pod-babashka-aws.jar"
    "-H:Name=pod-babashka-aws"
    "-H:+ReportExceptionStackTraces"
    "--initialize-at-build-time"
    "-H:EnableURLProtocols=http,https,jar"
    "--enable-all-security-services"
    "--report-unsupported-elements-at-runtime"
    "-H:ReflectionConfigurationFiles=reflection.json"
    "-H:ResourceConfigurationFiles=resources.json"
    "--verbose"
    "--no-fallback"
    "--no-server"
    "-J-Xmx3g"
    "pod.babashka.aws"
)

STATIC_COMPILE="${STATIC_COMPILE:-}"

if [ "$STATIC_COMPILE" = "true" ]; then
    args+=("--static" "--libc=musl")
fi

sudo cp /usr/lib/x86_64-linux-musl/lib/libz.a /usr/lib/gcc/x86_64-linux-gnu/8/
"$GRAALVM_HOME/bin/native-image" "${args[@]}"
